// Build step: inline site/ files into api/index.js and api/login.js so every
// page is served through a serverless function that enforces the session.
const fs = require('fs');
const path = require('path');

function esc(s) {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');
}

const site = path.join(__dirname, 'site');
const html = fs.readFileSync(path.join(site, 'index.html'), 'utf8');
const css = fs.readFileSync(path.join(site, 'styles.css'), 'utf8');
const js = fs.readFileSync(path.join(site, 'app.js'), 'utf8');
const page = html
  .replace('<!--STYLES-->', `<style>${css}</style>`)
  .replace('<!--APP-->', `<script>${js}</script>`);
const loginHtml = fs.readFileSync(path.join(site, 'login.html'), 'utf8');

const indexJs = `// GENERATED by build.js — do not edit by hand. Edit site/ instead.
const { getSessionEmail } = require('./_session');
const HTML = \`${esc(page)}\`;
module.exports = (req, res) => {
  const email = getSessionEmail(req, process.env.SESSION_SECRET || '');
  if (!email) {
    res.writeHead(302, { Location: '/login', 'Cache-Control': 'no-store' });
    res.end();
    return;
  }
  res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store' });
  res.end(HTML.split('__USER_EMAIL__').join(email));
};
`;

const loginJs = `// GENERATED by build.js — do not edit by hand. Edit site/login.html instead.
const HTML = \`${esc(loginHtml)}\`;
module.exports = (req, res) => {
  res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store' });
  res.end(HTML);
};
`;

fs.writeFileSync(path.join(__dirname, 'api', 'index.js'), indexJs);
fs.writeFileSync(path.join(__dirname, 'api', 'login.js'), loginJs);
console.log('built api/index.js and api/login.js');
