// GENERATED by build.js — do not edit by hand. Edit site/login.html instead.
const HTML = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Sign in — My Kanban Board</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: #fafafa; display: flex; align-items: center; justify-content: center; min-height: 100vh; margin: 0; }
  .box { background: #fff; border: 1px solid #e5e7eb; border-radius: 16px; padding: 2.5rem; text-align: center; max-width: 360px; box-shadow: 0 4px 16px rgba(0,0,0,.06); }
  h1 { font-size: 1.4rem; margin: 0 0 0.5rem; }
  p { color: #6b7280; font-size: 0.9rem; margin: 0 0 1.5rem; }
  .err { color: #b91c1c; font-size: 0.85rem; margin-bottom: 1rem; }
  #btn-wrap { display: flex; justify-content: center; }
</style>
</head>
<body>
  <div class="box">
    <h1>My Kanban Board</h1>
    <div class="err" id="err" style="display:none"></div>
    <p>This board is private. Sign in with Google to continue.</p>
    <div id="btn-wrap"></div>
  </div>
  <script>
    function showErr(msg) {
      const el = document.getElementById('err');
      el.style.display = 'block';
      el.textContent = msg;
    }
    fetch('/api/config')
      .then((r) => r.json())
      .then((cfg) => {
        if (!cfg.clientId) { showErr('Sign-in is not configured yet.'); return; }
        const s = document.createElement('script');
        s.src = 'https://accounts.google.com/gsi/client';
        s.async = true; s.defer = true;
        s.onload = () => {
          google.accounts.id.initialize({
            client_id: cfg.clientId,
            callback: (resp) => {
              fetch('/api/session', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ credential: resp.credential }),
              }).then((r) => {
                if (r.ok) location.href = '/';
                else r.json().then((j) => showErr(j.error === 'not_allowed' ? 'This Google account is not allowed on this board.' : 'Sign-in failed. Please try again.'));
              }).catch(() => showErr('Sign-in failed. Please try again.'));
            },
          });
          google.accounts.id.renderButton(document.getElementById('btn-wrap'), { theme: 'filled_black', size: 'large' });
        };
        document.head.appendChild(s);
      })
      .catch(() => showErr('Could not load sign-in configuration.'));
    const e = new URLSearchParams(location.search).get('error');
    if (e) showErr('Sign-in failed (' + e + '). Please try again.');
  </script>
</body>
</html>
`;
module.exports = (req, res) => {
  res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store' });
  res.end(HTML);
};
